{
    "name": "Society Management System",
    "depends": ["mail", ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/settings.xml",
        "views/user.xml",
        "views/tenant.xml",
        "views/rent.xml",
        "views/tower.xml",
        "views/apartment.xml",
        "views/floor.xml",
        "views/parking.xml",
        "views/owner.xml",
        "views/amenity.xml",
        "views/book_amenity.xml",
        "views/utility_bills.xml",
        "views/common_area_bills.xml",
        "views/maintenance.xml",
        "views/offline_req.xml",
        "views/assets.xml",
        "views/m_schedule.xml",
        "views/issue_report.xml",
        "views/tickets.xml",
        "views/notice_board.xml",
        "views/visitor.xml",
        "views/events.xml",
        "views/report.xml",
        "models/reports/report.xml",
        "models/reports/maintenance_report.xml",
        "models/reports/monthly_report.xml",
        "data/ir_sequence.xml",
        "data/rent_confirm_mail.xml",
        "settings/apartment_type_settings.xml",
        "settings/asset_category_settings.xml",
        "settings/bill_type_settings.xml",
        "settings/ticket_type.xml",
        "settings/currency_settings.xml",
        "settings/maintenance_settings.xml",
        "settings/visitors_type_settings.xml",
        "views/menu.xml",
    ]

}
