{
    "name": "Society Management System",
    "depends": [],
    "data": [
        "security/ir.model.access.csv",
        "views/settings.xml",
        "views/user.xml",
        "views/tenant.xml",
        "views/rent.xml",
        "views/tower.xml",
        "views/apartment.xml",
        "views/floor.xml",
        "views/parking.xml",
        "views/owner.xml",
        "views/amenity.xml",
        "views/book_amenity.xml",
        "views/utility_bills.xml",
        "views/common_area_bills.xml",
        "views/maintenance.xml",
        "settings/apartment_type_settings.xml",
        "settings/asset_category_settings.xml",
        "settings/bill_type_settings.xml",
        "settings/ticket_type.xml",
        "settings/currency_settings.xml",
        "settings/maintenance_settings.xml",
        "settings/visitors_type_settings.xml",
        "views/menu.xml",
    ]

}
